### ISSUE TITLE
usta nasıl indiricez

### ISSUE THREAD

**Issue by Ancienty** [UnioDex/CrateCreator2#1]
github dosyaları nasıl indiriliyor, rar yerine bunun .exeli hali falan yok mu iq'm yetmedi buna

**Comment by ygtdmn** [comment]
Bazı güncellemeler yaptım ve projeyi build ederek .jar dosyasını yayınladım. Buradan indirebilirsin:
https://github.com/UnioDex/CrateCreator/releases/download/3.0/CrateCreator.zip

Yakında uniocraft.com üzerinde bir konu açarak nasıl çalıştığını Türkçe olarak anlatabilirim. Şimdilik burayı okuyabilirsin:
https://github.com/UnioDex/CrateCreator/blob/master/README.md
